[package]
name = "amethyst-action-game-3d"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.10.0"
amethyst_gltf = "*"
gltf = "*"

[[bin]]
name = "action-game-3d"
path = "src/main.rs"

[[bin]]
name = "simple-level"
path = "src/simple_level.rs"
